
INSERT INTO ROLE VALUES(seq_role.nextval, 'Program Lead', 'Responsable du Programme');
INSERT INTO ROLE VALUES(seq_role.nextval, 'Program Officer', 'Agent de Programme');

INSERT INTO REVISION_INFO VALUES (2, '2020-01-01 00:00:00.00', 'N/A (PREPOPULATED)');
INSERT INTO ROLE_HISTORY VALUES (1, 2, 0, 'Program Lead', 'Responsable du Programme');
INSERT INTO ROLE_HISTORY VALUES (2, 2, 0, 'Program Officer', 'Agent de Programme');

INSERT INTO REVISION_INFO VALUES (4, '2020-01-01 00:00:00', 'N/A (PREPOPULATED)');
INSERT INTO AGENCY_HISTORY VALUES (1, 4, 0, 'SSHRC', 'CRSN', 'Social Sciences and Humanities Research Council', 'Conseil de Recherches en Sciences Humaines');
INSERT INTO AGENCY_HISTORY VALUES (2, 4, 0, 'NSERC', 'CRSNG', 'Natural Sciences and Engineering Research Council', STRINGDECODE('Conseil de Recherches en Sciences Naturelles et en G\u00e9nie'));
INSERT INTO AGENCY_HISTORY VALUES (3, 4, 0, 'CIHR', 'IRSC', 'Canadian Institutes of Health Research', STRINGDECODE('Instituts de Recherche en Sant\u00e9'));

INSERT INTO REVISION_INFO VALUES (5, '2020-01-01 00:00:00', 'N/A (PREPOPULATED)');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (1, 5, 0, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (2, 5, 0, 'CRM', 'CRM', 'CRM');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (3, 5, 0, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (4, 5, 0, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (5, 5, 0, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (6, 5, 0, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (7, 5, 0, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (8, 5, 0, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (9, 5, 0, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (10, 5, 0, 'SP Secure Upload', 'SharePoint Secure Upload', STRINGDECODE('T\u00e9l\u00e9chargement S\u00e9curis\u00e9 SharePoint'));
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (11, 5, 0, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');


INSERT INTO GENDER VALUES (SEQ_GENDER.NEXTVAL, 'Female', 'Femme');
INSERT INTO GENDER VALUES (SEQ_GENDER.NEXTVAL, 'Male', 'Homme');
INSERT INTO GENDER VALUES (SEQ_GENDER.NEXTVAL, 'Non-Binary', 'Non-Binaire');

INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'Latin American', 'Latino Américain');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'Caribbean', 'Caraïbes');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'Middle Eastern', 'Moyen Orient');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'Central Asian', 'Asie Centrale');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'East Asian', 'Asie de l''Est');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'South Asian', 'Sud-Asiatique');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'South East Asian', 'Asie du Sud Est');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'West Asian', 'Asie Occidentale');
INSERT INTO VISIBLE_MINORITY VALUES (SEQ_VISIBLE_MINORITY.NEXTVAL, 'African', 'Africain');

INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Métis', 'Métis');
INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Inuit', 'Inuit');
INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Mi''kmaq', 'Mi''kmaq');
INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Iroquois', 'Iroquois');
INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Haida', 'Haida');
INSERT INTO INDIGENOUS_IDENTITY VALUES (SEQ_INDIGENOUS_IDENTITY.NEXTVAL, 'Dalelh', 'Dalelh');

