INSERT INTO granting_capability (id, description, url, funding_opportunity_id, granting_stage_id, granting_system_id) VALUES
(1, NULL, NULL, 1, 2, 8),
(2, NULL, NULL, 2, 2, 8),
(3, NULL, NULL, 3, 2, 6),
(4, NULL, NULL, 4, 2, 6),
(5, NULL, NULL, 5, 2, 10),
(6, NULL, NULL, 6, 2, 10),
(7, NULL, NULL, 7, 2, 10),
(8, NULL, NULL, 8, 2, 10),
(9, NULL, NULL, 9, 2, 10),
(10, NULL, NULL, 10, 2, 10),
(11, NULL, NULL, 11, 2, 10),
(12, NULL, NULL, 12, 2, 10),
(13, NULL, NULL, 13, 2, 10),
(14, NULL, NULL, 14, 2, 10),
(15, NULL, NULL, 15, 2, 10),
(16, NULL, NULL, 16, 2, 10),
(17, NULL, NULL, 17, 2, 10),
(18, NULL, NULL, 18, 2, 10),
(19, NULL, NULL, 19, 2, 10),
(20, NULL, NULL, 20, 2, 10),
(21, NULL, NULL, 21, 2, 10),
(22, NULL, NULL, 22, 2, 10),
(23, NULL, NULL, 23, 2, 10),
(24, NULL, NULL, 24, 2, 5),
(25, NULL, NULL, 25, 2, 5),
(26, NULL, NULL, 26, 2, 5),
(27, NULL, NULL, 27, 2, 5),
(28, NULL, NULL, 28, 2, 5),
(29, NULL, NULL, 29, 2, 5),
(30, NULL, NULL, 30, 2, 5),
(31, NULL, NULL, 31, 2, 5),
(32, NULL, NULL, 32, 2, 5),
(33, NULL, NULL, 33, 2, 5),
(34, NULL, NULL, 34, 2, 5),
(35, NULL, NULL, 35, 2, 5),
(36, NULL, NULL, 36, 2, 5),
(37, NULL, NULL, 37, 2, 5),
(38, NULL, NULL, 38, 2, 5),
(39, NULL, NULL, 39, 2, 5),
(40, NULL, NULL, 40, 2, 5),
(41, NULL, NULL, 41, 2, 5),
(42, NULL, NULL, 42, 2, 5),
(43, NULL, NULL, 43, 2, 5),
(44, NULL, NULL, 44, 2, 5),
(45, NULL, NULL, 45, 2, 5),
(46, NULL, NULL, 46, 2, 5),
(47, NULL, NULL, 47, 2, 5),
(48, NULL, NULL, 48, 2, 5),
(49, NULL, NULL, 49, 2, 5),
(50, NULL, NULL, 50, 2, 1),
(51, NULL, NULL, 51, 2, 6),
(52, NULL, NULL, 52, 2, 10),
(53, NULL, NULL, 53, 2, 1),
(54, NULL, NULL, 54, 2, 1),
(55, NULL, NULL, 55, 2, 1),
(56, NULL, NULL, 56, 2, 1),
(57, NULL, NULL, 57, 2, 1),
(58, NULL, NULL, 58, 2, 1),
(59, NULL, NULL, 59, 2, 1),
(60, NULL, NULL, 60, 2, 1),
(61, NULL, NULL, 61, 2, 1),
(62, NULL, NULL, 62, 2, 10),
(63, NULL, NULL, 63, 2, 10),
(64, NULL, NULL, 64, 2, 10),
(65, NULL, NULL, 65, 2, 10),
(66, NULL, NULL, 66, 2, 10),
(67, NULL, NULL, 67, 2, 10),
(68, NULL, NULL, 68, 2, 10),
(69, NULL, NULL, 69, 2, 10),
(70, NULL, NULL, 70, 2, 10),
(71, NULL, NULL, 71, 2, 10),
(72, NULL, NULL, 72, 2, 10),
(73, NULL, NULL, 73, 2, 10),
(74, NULL, NULL, 74, 2, 10),
(75, NULL, NULL, 75, 2, 6),
(76, NULL, NULL, 76, 2, 6),
(77, NULL, NULL, 77, 2, 5),
(78, NULL, NULL, 78, 2, 5),
(79, NULL, NULL, 81, 2, 6),
(80, NULL, NULL, 82, 2, 7),
(81, NULL, NULL, 83, 2, 4),
(82, NULL, NULL, 84, 2, 4),
(83, NULL, NULL, 85, 2, 10),
(84, NULL, NULL, 86, 2, 10),
(85, NULL, NULL, 87, 2, 10),
(86, NULL, NULL, 88, 2, 4),
(87, NULL, NULL, 89, 2, 4),
(88, NULL, NULL, 90, 2, 4),
(89, NULL, NULL, 91, 2, 4),
(90, NULL, NULL, 92, 2, 4),
(91, NULL, NULL, 93, 2, 4),
(92, NULL, NULL, 94, 2, 1),
(93, NULL, NULL, 95, 2, 1),
(94, NULL, NULL, 96, 2, 10),
(95, NULL, NULL, 97, 2, 10),
(96, NULL, NULL, 98, 2, 3),
(97, NULL, NULL, 99, 2, 3),
(98, NULL, NULL, 100, 2, 3),
(99, NULL, NULL, 101, 2, 3),
(100, NULL, NULL, 102, 2, 3),
(101, NULL, NULL, 103, 2, 3),
(102, NULL, NULL, 104, 2, 3),
(103, NULL, NULL, 105, 2, 3),
(104, NULL, NULL, 106, 2, 3),
(105, NULL, NULL, 107, 2, 3),
(106, NULL, NULL, 108, 2, 3),
(107, NULL, NULL, 109, 2, 3),
(108, NULL, NULL, 110, 2, 3),
(109, NULL, NULL, 111, 2, 3),
(110, NULL, NULL, 112, 2, 3),
(111, NULL, NULL, 113, 2, 3),
(112, NULL, NULL, 114, 2, 3),
(113, NULL, NULL, 115, 2, 3),
(114, NULL, NULL, 116, 2, 4),
(115, NULL, NULL, 118, 2, 4),
(116, NULL, NULL, 119, 2, 4),
(117, NULL, NULL, 120, 2, 10),
(118, NULL, NULL, 121, 2, 7),
(119, NULL, NULL, 122, 2, 10),
(120, NULL, NULL, 123, 2, 10),
(121, NULL, NULL, 124, 2, 5),
(122, NULL, NULL, 125, 2, 5),
(123, NULL, NULL, 126, 2, 5),
(124, NULL, NULL, 127, 2, 4),
(125, NULL, NULL, 128, 2, 8),
(126, NULL, NULL, 129, 2, 8),
(127, NULL, NULL, 130, 2, 1),
(128, NULL, NULL, 131, 2, 10),
(129, NULL, NULL, 132, 2, 10),
(130, NULL, NULL, 133, 2, 10),
(131, NULL, NULL, 134, 2, 10),
(132, NULL, NULL, 135, 2, 10),
(133, NULL, NULL, 136, 2, 5),
(134, NULL, NULL, 137, 2, 10),
(135, NULL, NULL, 139, 2, 9),
(136, NULL, NULL, 140, 2, 9),
(137, NULL, NULL, 141, 2, 9),
(138, NULL, NULL, 1, 4, 6),
(139, NULL, NULL, 2, 4, 8),
(140, NULL, NULL, 3, 4, 6),
(141, NULL, NULL, 4, 4, 6);
INSERT INTO granting_capability VALUES
(142, NULL, NULL, 5, 4, 6),
(143, NULL, NULL, 6, 4, 6),
(144, NULL, NULL, 7, 4, 6),
(145, NULL, NULL, 8, 4, 6),
(146, NULL, NULL, 9, 4, 6),
(147, NULL, NULL, 10, 4, 6),
(148, NULL, NULL, 11, 4, 10),
(149, NULL, NULL, 12, 4, 6),
(150, NULL, NULL, 13, 4, 6),
(151, NULL, NULL, 14, 4, 6),
(152, NULL, NULL, 15, 4, 6),
(153, NULL, NULL, 16, 4, 6),
(154, NULL, NULL, 17, 4, 6),
(155, NULL, NULL, 18, 4, 6),
(156, NULL, NULL, 19, 4, 6),
(157, NULL, NULL, 20, 4, 10),
(158, NULL, NULL, 21, 4, 10),
(159, NULL, NULL, 22, 4, 6),
(160, NULL, NULL, 23, 4, 10),
(161, NULL, NULL, 24, 4, 6),
(162, NULL, NULL, 25, 4, 6),
(163, NULL, NULL, 26, 4, 6),
(164, NULL, NULL, 27, 4, 6),
(165, NULL, NULL, 28, 4, 6),
(166, NULL, NULL, 29, 4, 6),
(167, NULL, NULL, 30, 4, 6),
(168, NULL, NULL, 31, 4, 6),
(169, NULL, NULL, 32, 4, 6),
(170, NULL, NULL, 33, 4, 6),
(171, NULL, NULL, 34, 4, 6),
(172, NULL, NULL, 35, 4, 6),
(173, NULL, NULL, 36, 4, 6),
(174, NULL, NULL, 37, 4, 6),
(175, NULL, NULL, 38, 4, 6),
(176, NULL, NULL, 39, 4, 6),
(177, NULL, NULL, 40, 4, 5),
(178, NULL, NULL, 41, 4, 5),
(179, NULL, NULL, 42, 4, 6),
(180, NULL, NULL, 43, 4, 5),
(181, NULL, NULL, 44, 4, 5),
(182, NULL, NULL, 45, 4, 6),
(183, NULL, NULL, 46, 4, 6),
(184, NULL, NULL, 47, 4, 6),
(185, NULL, NULL, 48, 4, 6),
(186, NULL, NULL, 49, 4, 5),
(187, NULL, NULL, 50, 4, 1),
(188, NULL, NULL, 51, 4, 6),
(189, NULL, NULL, 52, 4, 6),
(190, NULL, NULL, 53, 4, 1),
(191, NULL, NULL, 54, 4, 6),
(192, NULL, NULL, 55, 4, 1),
(193, NULL, NULL, 56, 4, 1),
(194, NULL, NULL, 57, 4, 1),
(195, NULL, NULL, 58, 4, 1),
(196, NULL, NULL, 59, 4, 1),
(197, NULL, NULL, 60, 4, 1),
(198, NULL, NULL, 61, 4, 1),
(199, NULL, NULL, 62, 4, 6),
(200, NULL, NULL, 63, 4, 6),
(201, NULL, NULL, 64, 4, 6),
(202, NULL, NULL, 65, 4, 6),
(203, NULL, NULL, 66, 4, 6),
(204, NULL, NULL, 67, 4, 6),
(205, NULL, NULL, 68, 4, 10),
(206, NULL, NULL, 69, 4, 10),
(207, NULL, NULL, 70, 4, 10),
(208, NULL, NULL, 71, 4, 10),
(209, NULL, NULL, 72, 4, 10),
(210, NULL, NULL, 73, 4, 10),
(211, NULL, NULL, 74, 4, 10),
(212, NULL, NULL, 75, 4, 6),
(213, NULL, NULL, 76, 4, 6),
(214, NULL, NULL, 77, 4, 6),
(215, NULL, NULL, 78, 4, 6),
(216, NULL, NULL, 81, 4, 6),
(217, NULL, NULL, 82, 4, 7),
(218, NULL, NULL, 83, 4, 4),
(219, NULL, NULL, 84, 4, 4),
(220, NULL, NULL, 85, 4, 10),
(221, NULL, NULL, 86, 4, 10),
(222, NULL, NULL, 87, 4, 10),
(223, NULL, NULL, 88, 4, 4),
(224, NULL, NULL, 89, 4, 4),
(225, NULL, NULL, 90, 4, 4),
(226, NULL, NULL, 91, 4, 4),
(227, NULL, NULL, 92, 4, 4),
(228, NULL, NULL, 93, 4, 4),
(229, NULL, NULL, 94, 4, 1),
(230, NULL, NULL, 95, 4, 1),
(231, NULL, NULL, 96, 4, 4),
(232, NULL, NULL, 97, 4, 10),
(233, NULL, NULL, 98, 4, 4),
(234, NULL, NULL, 99, 4, 4),
(235, NULL, NULL, 100, 4, 4),
(236, NULL, NULL, 101, 4, 4),
(237, NULL, NULL, 102, 4, 3),
(238, NULL, NULL, 103, 4, 4),
(239, NULL, NULL, 104, 4, 3),
(240, NULL, NULL, 105, 4, 4),
(241, NULL, NULL, 106, 4, 4),
(242, NULL, NULL, 107, 4, 4),
(243, NULL, NULL, 108, 4, 4),
(244, NULL, NULL, 109, 4, 4),
(245, NULL, NULL, 110, 4, 4),
(246, NULL, NULL, 111, 4, 4),
(247, NULL, NULL, 112, 4, 4),
(248, NULL, NULL, 113, 4, 4),
(249, NULL, NULL, 114, 4, 4),
(250, NULL, NULL, 115, 4, 4),
(251, NULL, NULL, 116, 4, 4),
(252, NULL, NULL, 118, 4, 4),
(253, NULL, NULL, 119, 4, 4),
(254, NULL, NULL, 120, 4, 4),
(255, NULL, NULL, 121, 4, 7),
(256, NULL, NULL, 122, 4, 6),
(257, NULL, NULL, 122, 4, 4),
(258, NULL, NULL, 122, 4, 8),
(259, NULL, NULL, 123, 4, 6),
(260, NULL, NULL, 124, 4, 6),
(261, NULL, NULL, 125, 4, 6),
(262, NULL, NULL, 126, 4, 6),
(263, NULL, NULL, 127, 4, 4),
(264, NULL, NULL, 128, 4, 8),
(265, NULL, NULL, 129, 4, 8),
(266, NULL, NULL, 130, 4, 1),
(267, NULL, NULL, 131, 4, 6),
(268, NULL, NULL, 131, 4, 4),
(269, NULL, NULL, 131, 4, 8),
(270, NULL, NULL, 132, 4, 6),
(271, NULL, NULL, 132, 4, 4),
(272, NULL, NULL, 132, 4, 8),
(273, NULL, NULL, 133, 4, 6),
(274, NULL, NULL, 133, 4, 4),
(275, NULL, NULL, 133, 4, 8),
(276, NULL, NULL, 134, 4, 6),
(277, NULL, NULL, 134, 4, 4),
(278, NULL, NULL, 134, 4, 8),
(279, NULL, NULL, 135, 4, 6);
INSERT INTO granting_capability VALUES
(280, NULL, NULL, 136, 4, 5),
(281, NULL, NULL, 137, 4, 6),
(282, NULL, NULL, 139, 4, 9),
(283, NULL, NULL, 140, 4, 9),
(284, NULL, NULL, 141, 4, 9);

INSERT INTO "PUBLIC"."SYSTEM_FUNDING_OPPORTUNITY" VALUES
(seq_system_funding_opportunity.nextval, 'CTAC ', 'Technology Access Centre', STRINGDECODE('Centre d''acc\u00e8s \u00e0 la technologie'), 6, 35),
(seq_system_funding_opportunity.nextval, '612', 'Indigenous Research Capacity and Reconciliation - Connection Grants', STRINGDECODE('Subventions Connexion - Capacit\u00e9 de recherche autochtone et r\u00e9conciliation'), 2, 108),
(seq_system_funding_opportunity.nextval, '892', 'Partnership Engage Grants', 'Subventions d''engagement partenarial', 2, 102),
(seq_system_funding_opportunity.nextval, '435', 'Insight Grants', 'Subventions Savoir', 4, 17),
(seq_system_funding_opportunity.nextval, '752', 'Doctoral Awards', 'Bourses de doctorat', 4, 66),
(seq_system_funding_opportunity.nextval, '767', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Doctoral', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Doctorat'), 6, 117),
(seq_system_funding_opportunity.nextval, '766', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Master''s', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Ma\u00eetrise'), 6, 58),
(seq_system_funding_opportunity.nextval, '756', 'SSHRC Postdoctoral Fellowships', 'Bourses postdoctorales du CRSH', 4, 77),
(seq_system_funding_opportunity.nextval, '862', 'Sport Participation Research Initiative', 'Initiative de recherche sur la participation au sport', 6, 13),
(seq_system_funding_opportunity.nextval, '771', 'Canada Graduate Scholarships - Michael Smith Foreign Study Supplements', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada - Suppl\u00e9ments pour \u00e9tudes \u00e0 l''\u00e9tranger Michael-Smith'), 6, 41),
(seq_system_funding_opportunity.nextval, '872', 'Knowledge Synthesis Grants', STRINGDECODE('Subventions de synth\u00e8se des connaissances'), 2, 119),
(seq_system_funding_opportunity.nextval, '970', 'College and Community Innovation Program', STRINGDECODE('Programme d''innovation dans les coll\u00e8ges et la communaut\u00e9'), 4, 53),
(seq_system_funding_opportunity.nextval, '877', 'Department of National Defence Research Initiative (DNDRI)', STRINGDECODE('Initiative de recherche du minist\u00e8re de la D\u00e9fense nationale (IRMDN)'), 2, 126),
(seq_system_funding_opportunity.nextval, '220', 'Queen''s Fellowship Trust Fund', 'Bourses de la Reine - fonds en fiducie', 2, 80),
(seq_system_funding_opportunity.nextval, '754', 'Bora Laskin National Fellowship in Human Rights Research', 'Bourse canadienne Bora Laskin pour la recherche sur les droits de la personne', 6, 78),
(seq_system_funding_opportunity.nextval, '770', 'Vanier Canada Graduate Scholarships', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Vanier'), 4, 86),
(seq_system_funding_opportunity.nextval, '772', 'Banting Postdoctoral Fellowships', 'Bourse postdoctorale Banting', 4, 102),
(seq_system_funding_opportunity.nextval, 'CIRC ', 'Industrial Research Chairs for Colleges Grants', STRINGDECODE('Subventions de chaires de recherche industrielle dans les coll\u00e8ges'), 6, 75),
(seq_system_funding_opportunity.nextval, 'NCEGP', 'Networks of Centres of Excellence - Group', STRINGDECODE('R\u00e9seaux de centres d''excellence - groupe'), 6, 132),
(seq_system_funding_opportunity.nextval, 'IRCSA', 'Industrial Research Chairs - Regular - Salary', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - salaires'), 2, 18),
(seq_system_funding_opportunity.nextval, 'IRCPJ', 'Industrial Research Chairs - Regular - Research', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - recherche'), 4, 66),
(seq_system_funding_opportunity.nextval, 'CRDPJ', 'Collaborative Research and Development Grants - Project', STRINGDECODE('Subventions de recherche et d\u00e9veloppement coop\u00e9rative - projet'), 6, 99),
(seq_system_funding_opportunity.nextval, 'VFG3 ', 'Visiting Fellowships in Canadian Government Laboratories - 3rd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 3e ann\u00e9e'), 4, 86),
(seq_system_funding_opportunity.nextval, 'VFG2 ', 'Visiting Fellowships in Canadian Government Laboratories - 2nd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 2e ann\u00e9e'), 6, 73),
(seq_system_funding_opportunity.nextval, 'JCP  ', 'John C. Polanyi Award', 'Le Prix John-C.-Polanyi', 2, 71),
(seq_system_funding_opportunity.nextval, 'BCPIR', 'Brockhouse Canada Prize for Interdisciplinary Research in Science and Engineering', STRINGDECODE('Prix Brockhouse du Canada pour la recherche interdisciplinaire en sciences et en g\u00e9nie'), 2, 64),
(seq_system_funding_opportunity.nextval, 'GLDSU', 'Gerhard Herzberg Canada Gold Medal for Science and Engineering', STRINGDECODE('M\u00e9daille d''or Gerhard-Herzberg en sciences et en g\u00e9nie du Canada'), 4, 68),
(seq_system_funding_opportunity.nextval, 'CREAT', 'Collaborative Research and Training Experience', STRINGDECODE('\"Programme de formation orient\u00e9e vers la nouveaut\u00e9'), 2, 103);
INSERT INTO "PUBLIC"."SYSTEM_FUNDING_OPPORTUNITY" VALUES
(seq_system_funding_opportunity.nextval, 'SMFSA', 'EWR Steacie Fellowships - Salary', 'EWR Steacie - salaires', 6, 48),
(seq_system_funding_opportunity.nextval, 'PDF  ', 'Postdoctoral Fellowships - 1st and 2nd years', STRINGDECODE('Bourses postdoctorales - 1re et 2e ann\u00e9es'), 6, 24),
(seq_system_funding_opportunity.nextval, 'USRAI', 'Industrial Undergraduate Student Research Awards Program', 'Programme de bourses de recherche de 1er cycle en milieu industriel', 2, 8),
(seq_system_funding_opportunity.nextval, 'RGPST', 'Discovery Grants Program - Ship Time', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - temps navire'), 4, 95),
(seq_system_funding_opportunity.nextval, 'PGSD3', 'Postgraduate Scholarships D - 3 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 3 ans'), 6, 74),
(seq_system_funding_opportunity.nextval, 'URU  ', 'University Undergraduate Student Research Awards', 'Bourses de recherche de 1er cycle en milieu universitaire', 2, 76),
(seq_system_funding_opportunity.nextval, 'CGSD3', 'Alexander Graham Bell Canada Graduate Scholarship D - 3 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 3 ans'), 4, 124),
(seq_system_funding_opportunity.nextval, 'PGSD2', 'Postgraduate Scholarships D - 2 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 2 ans'), 6, 128),
(seq_system_funding_opportunity.nextval, 'STPGP', 'Strategic Projects - Group', STRINGDECODE('Projets strat\u00e9giques - groupe'), 2, 36),
(seq_system_funding_opportunity.nextval, 'RGPNS', 'Discovery Grants Program - Northern Research Supplement', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - suppl\u00e9ment en recherche nordique'), 2, 16),
(seq_system_funding_opportunity.nextval, 'CGSD2', 'Alexander Graham Bell Canada Graduate Scholarship D - 2 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 2 ans'), 4, 126),
(seq_system_funding_opportunity.nextval, 'EGP2 ', 'Engage Plus Grants for universities', STRINGDECODE('Subvention d''engagement partenarial Plus pour les universit\u00e9s'), 4, 117),
(seq_system_funding_opportunity.nextval, 'VFG1 ', 'Visiting Fellowships in Canadian Government Laboratories - 1st year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien -1re ann\u00e9e'), 6, 120),
(seq_system_funding_opportunity.nextval, 'I2IPJ', 'Idea to Innovation', STRINGDECODE('De l''id\u00e9e \u00e0 l''innovation'), 6, 75),
(seq_system_funding_opportunity.nextval, 'SIT  ', 'Summer Program in Taiwan', STRINGDECODE('Programme de stages d''\u00e9t\u00e9 \u00e0 Taiwan'), 6, 13),
(seq_system_funding_opportunity.nextval, '611', 'Connection Grants', 'Subventions Connexion', 4, 107),
(seq_system_funding_opportunity.nextval, '612', 'Indigenous Research Capacity and Reconciliation - Connection Grants', STRINGDECODE('Subventions Connexion - Capacit\u00e9 de recherche autochtone et r\u00e9conciliation'), 2, 114),
(seq_system_funding_opportunity.nextval, '892', 'Partnership Engage Grants', 'Subventions d''engagement partenarial', 4, 8),
(seq_system_funding_opportunity.nextval, '435', 'Insight Grants', 'Subventions Savoir', 6, 49),
(seq_system_funding_opportunity.nextval, '752', 'Doctoral Awards', 'Bourses de doctorat', 2, 98),
(seq_system_funding_opportunity.nextval, '767', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Doctoral', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Doctorat'), 2, 94),
(seq_system_funding_opportunity.nextval, '766', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Master''s', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Ma\u00eetrise'), 4, 83),
(seq_system_funding_opportunity.nextval, '756', 'SSHRC Postdoctoral Fellowships', 'Bourses postdoctorales du CRSH', 4, 12),
(seq_system_funding_opportunity.nextval, '862', 'Sport Participation Research Initiative', 'Initiative de recherche sur la participation au sport', 2, 133),
(seq_system_funding_opportunity.nextval, '771', 'Canada Graduate Scholarships - Michael Smith Foreign Study Supplements', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada - Suppl\u00e9ments pour \u00e9tudes \u00e0 l''\u00e9tranger Michael-Smith'), 4, 115),
(seq_system_funding_opportunity.nextval, '872', 'Knowledge Synthesis Grants', STRINGDECODE('Subventions de synth\u00e8se des connaissances'), 6, 46),
(seq_system_funding_opportunity.nextval, '970', 'College and Community Innovation Program', STRINGDECODE('Programme d''innovation dans les coll\u00e8ges et la communaut\u00e9'), 6, 88),
(seq_system_funding_opportunity.nextval, '877', 'Department of National Defence Research Initiative (DNDRI)', STRINGDECODE('Initiative de recherche du minist\u00e8re de la D\u00e9fense nationale (IRMDN)'), 2, 16),
(seq_system_funding_opportunity.nextval, '220', 'Queen''s Fellowship Trust Fund', 'Bourses de la Reine - fonds en fiducie', 6, 119),
(seq_system_funding_opportunity.nextval, '754', 'Bora Laskin National Fellowship in Human Rights Research', 'Bourse canadienne Bora Laskin pour la recherche sur les droits de la personne', 4, 139);
INSERT INTO "PUBLIC"."SYSTEM_FUNDING_OPPORTUNITY" VALUES
(seq_system_funding_opportunity.nextval, '770', 'Vanier Canada Graduate Scholarships', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Vanier'), 6, 57),
(seq_system_funding_opportunity.nextval, '772', 'Banting Postdoctoral Fellowships', 'Bourse postdoctorale Banting', 6, 129),
(seq_system_funding_opportunity.nextval, 'CTAC ', 'Technology Access Centre', STRINGDECODE('Centre d''acc\u00e8s \u00e0 la technologie'), 2, 44),
(seq_system_funding_opportunity.nextval, 'CIRC ', 'Industrial Research Chairs for Colleges Grants', STRINGDECODE('Subventions de chaires de recherche industrielle dans les coll\u00e8ges'), 2, 64),
(seq_system_funding_opportunity.nextval, 'NCEGP', 'Networks of Centres of Excellence - Group', STRINGDECODE('R\u00e9seaux de centres d''excellence - groupe'), 4, 129),
(seq_system_funding_opportunity.nextval, 'IRCSA', 'Industrial Research Chairs - Regular - Salary', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - salaires'), 6, 54),
(seq_system_funding_opportunity.nextval, 'IRCPJ', 'Industrial Research Chairs - Regular - Research', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - recherche'), 6, 3),
(seq_system_funding_opportunity.nextval, 'CRDPJ', 'Collaborative Research and Development Grants - Project', STRINGDECODE('Subventions de recherche et d\u00e9veloppement coop\u00e9rative - projet'), 6, 104),
(seq_system_funding_opportunity.nextval, 'VFG3 ', 'Visiting Fellowships in Canadian Government Laboratories - 3rd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 3e ann\u00e9e'), 2, 131),
(seq_system_funding_opportunity.nextval, 'VFG2 ', 'Visiting Fellowships in Canadian Government Laboratories - 2nd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 2e ann\u00e9e'), 4, 10),
(seq_system_funding_opportunity.nextval, 'JCP  ', 'John C. Polanyi Award', 'Le Prix John-C.-Polanyi', 2, 129),
(seq_system_funding_opportunity.nextval, 'BCPIR', 'Brockhouse Canada Prize for Interdisciplinary Research in Science and Engineering', STRINGDECODE('Prix Brockhouse du Canada pour la recherche interdisciplinaire en sciences et en g\u00e9nie'), 6, 17),
(seq_system_funding_opportunity.nextval, 'GLDSU', 'Gerhard Herzberg Canada Gold Medal for Science and Engineering', STRINGDECODE('M\u00e9daille d''or Gerhard-Herzberg en sciences et en g\u00e9nie du Canada'), 2, 134),
(seq_system_funding_opportunity.nextval, 'CREAT', 'Collaborative Research and Training Experience', STRINGDECODE('\"Programme de formation orient\u00e9e vers la nouveaut\u00e9'), 2, 136),
(seq_system_funding_opportunity.nextval, 'SMFSA', 'EWR Steacie Fellowships - Salary', 'EWR Steacie - salaires', 2, 120),
(seq_system_funding_opportunity.nextval, 'PDF  ', 'Postdoctoral Fellowships - 1st and 2nd years', STRINGDECODE('Bourses postdoctorales - 1re et 2e ann\u00e9es'), 6, 106),
(seq_system_funding_opportunity.nextval, 'USRAI', 'Industrial Undergraduate Student Research Awards Program', 'Programme de bourses de recherche de 1er cycle en milieu industriel', 4, 48),
(seq_system_funding_opportunity.nextval, 'RGPST', 'Discovery Grants Program - Ship Time', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - temps navire'), 4, 82),
(seq_system_funding_opportunity.nextval, 'PGSD3', 'Postgraduate Scholarships D - 3 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 3 ans'), 6, 1),
(seq_system_funding_opportunity.nextval, 'URU  ', 'University Undergraduate Student Research Awards', 'Bourses de recherche de 1er cycle en milieu universitaire', 6, 11),
(seq_system_funding_opportunity.nextval, 'CGSD3', 'Alexander Graham Bell Canada Graduate Scholarship D - 3 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 3 ans'), 6, 55),
(seq_system_funding_opportunity.nextval, 'PGSD2', 'Postgraduate Scholarships D - 2 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 2 ans'), 2, 102),
(seq_system_funding_opportunity.nextval, 'STPGP', 'Strategic Projects - Group', STRINGDECODE('Projets strat\u00e9giques - groupe'), 6, 13),
(seq_system_funding_opportunity.nextval, 'RGPNS', 'Discovery Grants Program - Northern Research Supplement', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - suppl\u00e9ment en recherche nordique'), 2, 94),
(seq_system_funding_opportunity.nextval, 'CGSD2', 'Alexander Graham Bell Canada Graduate Scholarship D - 2 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 2 ans'), 4, 37),
(seq_system_funding_opportunity.nextval, 'EGP2 ', 'Engage Plus Grants for universities', STRINGDECODE('Subvention d''engagement partenarial Plus pour les universit\u00e9s'), 6, 66),
(seq_system_funding_opportunity.nextval, 'VFG1 ', 'Visiting Fellowships in Canadian Government Laboratories - 1st year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien -1re ann\u00e9e'), 2, 74);
INSERT INTO "PUBLIC"."SYSTEM_FUNDING_OPPORTUNITY" VALUES
(seq_system_funding_opportunity.nextval, 'I2IPJ', 'Idea to Innovation', STRINGDECODE('De l''id\u00e9e \u00e0 l''innovation'), 4, 54),
(seq_system_funding_opportunity.nextval, 'SIT  ', 'Summer Program in Taiwan', STRINGDECODE('Programme de stages d''\u00e9t\u00e9 \u00e0 Taiwan'), 4, 45),
(seq_system_funding_opportunity.nextval, '611', 'Connection Grants', 'Subventions Connexion', 4, 74),
(seq_system_funding_opportunity.nextval, '612', 'Indigenous Research Capacity and Reconciliation - Connection Grants', STRINGDECODE('Subventions Connexion - Capacit\u00e9 de recherche autochtone et r\u00e9conciliation'), 6, 135),
(seq_system_funding_opportunity.nextval, '892', 'Partnership Engage Grants', 'Subventions d''engagement partenarial', 6, 47),
(seq_system_funding_opportunity.nextval, '435', 'Insight Grants', 'Subventions Savoir', 6, 72),
(seq_system_funding_opportunity.nextval, '752', 'Doctoral Awards', 'Bourses de doctorat', 4, 22),
(seq_system_funding_opportunity.nextval, '767', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Doctoral', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Doctorat'), 6, 105),
(seq_system_funding_opportunity.nextval, '766', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Master''s', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Ma\u00eetrise'), 2, 23),
(seq_system_funding_opportunity.nextval, '756', 'SSHRC Postdoctoral Fellowships', 'Bourses postdoctorales du CRSH', 2, 114),
(seq_system_funding_opportunity.nextval, '862', 'Sport Participation Research Initiative', 'Initiative de recherche sur la participation au sport', 6, 49),
(seq_system_funding_opportunity.nextval, '771', 'Canada Graduate Scholarships - Michael Smith Foreign Study Supplements', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada - Suppl\u00e9ments pour \u00e9tudes \u00e0 l''\u00e9tranger Michael-Smith'), 2, 94),
(seq_system_funding_opportunity.nextval, '872', 'Knowledge Synthesis Grants', STRINGDECODE('Subventions de synth\u00e8se des connaissances'), 4, 79),
(seq_system_funding_opportunity.nextval, '970', 'College and Community Innovation Program', STRINGDECODE('Programme d''innovation dans les coll\u00e8ges et la communaut\u00e9'), 4, 124),
(seq_system_funding_opportunity.nextval, '877', 'Department of National Defence Research Initiative (DNDRI)', STRINGDECODE('Initiative de recherche du minist\u00e8re de la D\u00e9fense nationale (IRMDN)'), 4, 110),
(seq_system_funding_opportunity.nextval, '220', 'Queen''s Fellowship Trust Fund', 'Bourses de la Reine - fonds en fiducie', 6, 84),
(seq_system_funding_opportunity.nextval, '754', 'Bora Laskin National Fellowship in Human Rights Research', 'Bourse canadienne Bora Laskin pour la recherche sur les droits de la personne', 6, 122),
(seq_system_funding_opportunity.nextval, '770', 'Vanier Canada Graduate Scholarships', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Vanier'), 2, 99),
(seq_system_funding_opportunity.nextval, '772', 'Banting Postdoctoral Fellowships', 'Bourse postdoctorale Banting', 6, 71),
(seq_system_funding_opportunity.nextval, 'CTAC ', 'Technology Access Centre', STRINGDECODE('Centre d''acc\u00e8s \u00e0 la technologie'), 4, 115),
(seq_system_funding_opportunity.nextval, 'CIRC ', 'Industrial Research Chairs for Colleges Grants', STRINGDECODE('Subventions de chaires de recherche industrielle dans les coll\u00e8ges'), 6, 47),
(seq_system_funding_opportunity.nextval, 'NCEGP', 'Networks of Centres of Excellence - Group', STRINGDECODE('R\u00e9seaux de centres d''excellence - groupe'), 2, 84),
(seq_system_funding_opportunity.nextval, 'IRCSA', 'Industrial Research Chairs - Regular - Salary', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - salaires'), 2, 44),
(seq_system_funding_opportunity.nextval, 'IRCPJ', 'Industrial Research Chairs - Regular - Research', STRINGDECODE('Professeurs-chercheurs industriels - r\u00e9guli\u00e8res - recherche'), 2, 2),
(seq_system_funding_opportunity.nextval, 'CRDPJ', 'Collaborative Research and Development Grants - Project', STRINGDECODE('Subventions de recherche et d\u00e9veloppement coop\u00e9rative - projet'), 4, 5),
(seq_system_funding_opportunity.nextval, 'VFG3 ', 'Visiting Fellowships in Canadian Government Laboratories - 3rd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 3e ann\u00e9e'), 4, 137),
(seq_system_funding_opportunity.nextval, 'VFG2 ', 'Visiting Fellowships in Canadian Government Laboratories - 2nd year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien - 2e ann\u00e9e'), 6, 88),
(seq_system_funding_opportunity.nextval, 'JCP  ', 'John C. Polanyi Award', 'Le Prix John-C.-Polanyi', 6, 140),
(seq_system_funding_opportunity.nextval, 'BCPIR', 'Brockhouse Canada Prize for Interdisciplinary Research in Science and Engineering', STRINGDECODE('Prix Brockhouse du Canada pour la recherche interdisciplinaire en sciences et en g\u00e9nie'), 6, 80);
INSERT INTO "PUBLIC"."SYSTEM_FUNDING_OPPORTUNITY" VALUES
(seq_system_funding_opportunity.nextval, 'GLDSU', 'Gerhard Herzberg Canada Gold Medal for Science and Engineering', STRINGDECODE('M\u00e9daille d''or Gerhard-Herzberg en sciences et en g\u00e9nie du Canada'), 2, 60),
(seq_system_funding_opportunity.nextval, 'CREAT', 'Collaborative Research and Training Experience', STRINGDECODE('\"Programme de formation orient\u00e9e vers la nouveaut\u00e9'), 2, 133),
(seq_system_funding_opportunity.nextval, 'SMFSA', 'EWR Steacie Fellowships - Salary', 'EWR Steacie - salaires', 6, 59),
(seq_system_funding_opportunity.nextval, 'PDF  ', 'Postdoctoral Fellowships - 1st and 2nd years', STRINGDECODE('Bourses postdoctorales - 1re et 2e ann\u00e9es'), 4, 20),
(seq_system_funding_opportunity.nextval, 'USRAI', 'Industrial Undergraduate Student Research Awards Program', 'Programme de bourses de recherche de 1er cycle en milieu industriel', 4, 96),
(seq_system_funding_opportunity.nextval, 'RGPST', 'Discovery Grants Program - Ship Time', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - temps navire'), 6, 44),
(seq_system_funding_opportunity.nextval, 'PGSD3', 'Postgraduate Scholarships D - 3 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 3 ans'), 2, 116),
(seq_system_funding_opportunity.nextval, 'URU  ', 'University Undergraduate Student Research Awards', 'Bourses de recherche de 1er cycle en milieu universitaire', 2, 91),
(seq_system_funding_opportunity.nextval, 'CGSD3', 'Alexander Graham Bell Canada Graduate Scholarship D - 3 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 3 ans'), 4, 9),
(seq_system_funding_opportunity.nextval, 'PGSD2', 'Postgraduate Scholarships D - 2 years', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures D - 2 ans'), 6, 78),
(seq_system_funding_opportunity.nextval, 'STPGP', 'Strategic Projects - Group', STRINGDECODE('Projets strat\u00e9giques - groupe'), 6, 9),
(seq_system_funding_opportunity.nextval, 'RGPNS', 'Discovery Grants Program - Northern Research Supplement', STRINGDECODE('Programme de subventions \u00e0 la d\u00e9couverte - suppl\u00e9ment en recherche nordique'), 6, 116),
(seq_system_funding_opportunity.nextval, 'CGSD2', 'Alexander Graham Bell Canada Graduate Scholarship D - 2 years', STRINGDECODE('Bourse d''\u00e9tudes sup\u00e9rieures du Canada Alexander-Graham-Bell D - 2 ans'), 2, 68),
(seq_system_funding_opportunity.nextval, 'EGP2 ', 'Engage Plus Grants for universities', STRINGDECODE('Subvention d''engagement partenarial Plus pour les universit\u00e9s'), 4, 106),
(seq_system_funding_opportunity.nextval, 'VFG1 ', 'Visiting Fellowships in Canadian Government Laboratories - 1st year', STRINGDECODE('Bourses de recherche scientifique dans les laboratoires du gouvernement canadien -1re ann\u00e9e'), 6, 69),
(seq_system_funding_opportunity.nextval, 'I2IPJ', 'Idea to Innovation', STRINGDECODE('De l''id\u00e9e \u00e0 l''innovation'), 4, 79),
(seq_system_funding_opportunity.nextval, 'SIT  ', 'Summer Program in Taiwan', STRINGDECODE('Programme de stages d''\u00e9t\u00e9 \u00e0 Taiwan'), 2, 99),
(seq_system_funding_opportunity.nextval, '611', 'Connection Grants', 'Subventions Connexion', 2, 81),
(seq_system_funding_opportunity.nextval, '612', 'Indigenous Research Capacity and Reconciliation - Connection Grants', STRINGDECODE('Subventions Connexion - Capacit\u00e9 de recherche autochtone et r\u00e9conciliation'), 2, 78),
(seq_system_funding_opportunity.nextval, '892', 'Partnership Engage Grants', 'Subventions d''engagement partenarial', 6, 3),
(seq_system_funding_opportunity.nextval, '435', 'Insight Grants', 'Subventions Savoir', 4, 133),
(seq_system_funding_opportunity.nextval, '752', 'Doctoral Awards', 'Bourses de doctorat', 6 , 89),
(seq_system_funding_opportunity.nextval, '767', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Doctoral', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Doctorat'), 6, 44),
(seq_system_funding_opportunity.nextval, '766', 'Joseph-Armand Bombardier Canada Graduate Scholarships - Master''s', STRINGDECODE('Bourses d''\u00e9tudes sup\u00e9rieures du Canada Joseph-Armand-Bombardier - Ma\u00eetrise'), 6, 107),
(seq_system_funding_opportunity.nextval, '756', 'SSHRC Postdoctoral Fellowships', 'Bourses postdoctorales du CRSH', 4, 58),
(seq_system_funding_opportunity.nextval, '862', 'Sport Participation Research Initiative', 'Initiative de recherche sur la participation au sport', 2, 104);
